### ISSUE TITLE
How build Benchmarks project ?

### ISSUE THREAD

**Issue by KANekT** [ImmediatePlatform/Immediate.Handlers#137]
I copy code from repo and build it:

0>Immediate.Handlers.Shared.csproj: Error NU1507 : Warning As Error: There are 2 package sources defined in your configuration. When using central package management, please map your package sources with package source mapping (https://aka.ms/nuget-package-source-mapping) or specify a single package source. The following sources are defined: nuget.org

**Comment by viceroypenguin** [comment]
Without more code, I cannot be certain what is missing in your setup, but I would encourage you to read <https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management>, as IH relies on CPM for nuget package version management. Sounds like you have an issue with what you have set up with regards to the CPM expectations of the IH csproj files.

**Comment by KANekT** [comment]
I'm not change code - only clone and run on Rider

**Comment by KANekT** [comment]
I find 
https://github.com/ImmediatePlatform/Immediate.Handlers/blob/cfb783a656127921c410d8f642c845450bc9982a/Directory.Packages.props#L3

if false = I can build project

**Comment by viceroypenguin** [comment]
> I'm not change code - only clone this repo and run on Rider
> 
> You not change nuget.config on you PC ? may be add setting in

No. My computer is standard, and I just opened Rider on the project and it builds fine. Please ensure that you are not using a custom nuget.config anywhere that may be influencing the CPM to demand package source. 

Note again the error: "There are 2 package sources defined in your configuration.". If you look, there is no nuget.config in the repository anywhere, so for additional sources to be defined, your machine must be doing so.

**Comment by KANekT** [comment]
Thank you

**Comment by KANekT** [comment]
BenchmarkDotNet v0.14.0, macOS Sequoia 15.0.1 (24A348) [Darwin 24.0.0]
Apple M2 Pro, 1 CPU, 10 logical and 10 physical cores
.NET SDK 8.0.200
  [Host]     : .NET 8.0.2 (8.0.224.6711), Arm64 RyuJIT AdvSIMD
  DefaultJob : .NET 8.0.2 (8.0.224.6711), Arm64 RyuJIT AdvSIMD


| Method                                   | Mean      | Error    | StdDev   | Ratio | RatioSD | Rank | Gen0   | Allocated | Alloc Ratio |
|----------------------------------------- |----------:|---------:|---------:|------:|--------:|-----:|-------:|----------:|------------:|
| SendRequest_Baseline                     |  39.66 ns | 0.478 ns | 0.447 ns |  1.00 |    0.02 |    1 | 0.0048 |      40 B |        1.00 |
| SendRequest_ImmediateHandler             |  56.63 ns | 0.332 ns | 0.278 ns |  1.43 |    0.02 |    2 | 0.0048 |      40 B |        1.00 |
| SendRequest_ImmediateHandler_Abstraction |  57.41 ns | 1.022 ns | 1.050 ns |  1.45 |    0.03 |    2 | 0.0048 |      40 B |        1.00 |
| SendRequest_Mediator                     |  65.08 ns | 0.800 ns | 0.748 ns |  1.64 |    0.03 |    3 | 0.0048 |      40 B |        1.00 |
| SendRequest_IMediator                    |  88.24 ns | 0.414 ns | 0.367 ns |  2.23 |    0.03 |    4 | 0.0048 |      40 B |        1.00 |
| SendRequest_MediatR                      | 184.28 ns | 0.537 ns | 0.503 ns |  4.65 |    0.05 |    5 | 0.0668 |     560 B |       14.00 |

| Method                                   | Mean      | Error    | StdDev   | Ratio | RatioSD | Rank | Gen0   | Allocated | Alloc Ratio |
|----------------------------------------- |----------:|---------:|---------:|------:|--------:|-----:|-------:|----------:|------------:|
| SendRequest_Baseline                     |  38.76 ns | 0.457 ns | 0.428 ns |  1.00 |    0.02 |    1 | 0.0048 |      40 B |        1.00 |
| SendRequest_ImmediateHandler_Abstraction |  58.38 ns | 0.095 ns | 0.089 ns |  1.51 |    0.02 |    2 | 0.0048 |      40 B |        1.00 |
| SendRequest_ImmediateHandler             |  61.40 ns | 0.830 ns | 0.776 ns |  1.58 |    0.03 |    3 | 0.0048 |      40 B |        1.00 |
| SendRequest_Mediator                     |  65.74 ns | 0.202 ns | 0.179 ns |  1.70 |    0.02 |    4 | 0.0048 |      40 B |        1.00 |
| SendRequest_IMediator                    |  77.79 ns | 0.319 ns | 0.299 ns |  2.01 |    0.02 |    5 | 0.0048 |      40 B |        1.00 |
| SendRequest_MediatR                      | 182.14 ns | 0.683 ns | 0.639 ns |  4.70 |    0.05 |    6 | 0.0668 |     560 B |       14.00 |

**Comment by viceroypenguin** [comment]
FYI, 8.0.2 is not the current version of net8- you should stay current and update to 8.0.10
